import { StartupIdea } from '../types';

export function generateIdeaMarkdown(idea: StartupIdea): string {
  const analysis = idea.analysis;
  const critic = idea.criticMode;
  const prompt = idea.projectPrompt;

  return `# ${idea.title} - FounderOS Executive Brief
> ${idea.oneSentenceDescription}

**Status:** ${analysis ? analysis.shouldBuild : 'UNANALYZED'} | **Overall OS Score:** ${analysis ? `${analysis.overallScore}/100` : 'N/A'}  
**Created:** ${new Date(idea.createdAt).toLocaleDateString()} | **Last Updated:** ${new Date(idea.updatedAt).toLocaleDateString()}  
**Tags:** ${idea.tags.join(', ')}

---

## 1. Core Idea Specifications

### Problem
${idea.problem}

### Target Users
${idea.targetUsers}

### Solution
${idea.solution}

### Why Now?
${idea.whyNow}

### Market Size & TAM
${idea.marketSize}

### Competitors & Alternatives
${idea.competitors}

### Competitive Advantage / Moat
${idea.competitiveAdvantage}

### Business Model & Pricing
${idea.businessModel}  
**Monetization Details:** ${idea.monetization}

### MVP Scope
${idea.mvp}

### Future Roadmap
${idea.futureRoadmap}

### Primary Risks & Failure Modes
**General Risks:** ${idea.risks}  
**Why This Could Fail:** ${idea.whyCouldFail}

### Personal Motivation & Notes
**Founder Motivation:** ${idea.personalMotivation}  
**Notes:** ${idea.notes}

---

${analysis ? `## 2. AI Investor Analysis & Scorecard

**Verdict:** \`${analysis.shouldBuild}\`  
**Verdict Rationale:** ${analysis.verdictRationale}

### Quantitative Score Matrix (0-100)
- **Market Need:** ${analysis.scores.marketNeed}/100
- **Originality:** ${analysis.scores.originality}/100
- **Competition Favorability:** ${analysis.scores.competition}/100
- **Execution Feasibility:** ${analysis.scores.difficulty}/100
- **Monetization Potential:** ${analysis.scores.monetization}/100
- **Scalability:** ${analysis.scores.scalability}/100
- **Founder-Market Fit:** ${analysis.scores.founderFit}/100
- **Technical Feasibility:** ${analysis.scores.technicalComplexity}/100
- **GTM Feasibility:** ${analysis.scores.goToMarketDifficulty}/100
- **AI Value Multiplier:** ${analysis.scores.aiValue}/100

### Key Strengths
${analysis.strengths.map(s => `- ${s}`).join('\n')}

### Key Weaknesses
${analysis.weaknesses.map(w => `- ${w}`).join('\n')}

### Hidden Risks
${analysis.hiddenRisks.map(r => `- ${r}`).join('\n')}

### Market Intelligence
- **Similar Products:** ${analysis.similarProducts.join(', ')}
- **Possible Competitors:** ${analysis.possibleCompetitors.join(', ')}
- **Target Buyer Personas:** ${analysis.potentialCustomers.join(', ')}

### Recommendations
- **Single Biggest Mistake to Avoid:** ${analysis.biggestMistake}
- **Recommended MVP Strategy:** ${analysis.mvpRecommendation}
- **Ways to Improve Viability:**
${analysis.waysToImprove.map(w => `  - ${w}`).join('\n')}

---
` : ''}

${critic ? `## 3. Investor Critic Mode (Assumption Challenges)

**Investor Persona:** ${critic.investorPersona}

### Existential Threat Checks
- **OpenAI / Big Tech Threat:** ${critic.openaiThreat}
- **Status Quo / Excel Threat:** ${critic.statusQuoThreat}
- **First 100 Paying Users Challenge:** ${critic.first100UsersChallenge}
- **Monetization Hurdle:** ${critic.monetizationHurdle}

### Challenged Key Assumptions
${critic.keyAssumptionsChallenged.map((item, idx) => `
#### Assumption #${idx + 1} [Severity: ${item.severity}]
- **Assumption:** ${item.assumption}
- **Investor Challenge:** ${item.challenge}
${item.founderResponse ? `- **Founder Counter-Argument:** ${item.founderResponse}` : ''}
${item.aiCritique ? `- **AI Critique (${item.critiqueVerdict}):** ${item.aiCritique}` : ''}
`).join('\n')}

---
` : ''}

${idea.questions && idea.questions.length > 0 ? `## 4. 10 Strategic Investor Questions

${idea.questions.map(q => `
### Q${q.id} [${q.category}]: ${q.question}
${q.founderAnswer ? `**Founder Answer:** ${q.founderAnswer}` : '*Unanswered*'}
${q.aiFeedback ? `**AI Feedback:** ${q.aiFeedback}` : ''}
`).join('\n')}

---
` : ''}

${prompt ? `## 5. Master Development Prompt (${prompt.targetTool.toUpperCase()})

\`\`\`markdown
${prompt.fullPromptText}
\`\`\`
` : ''}

*Report generated by FounderOS - The Operating System for Startup Founders.*
`;
}

export function downloadMarkdown(idea: StartupIdea) {
  const content = generateIdeaMarkdown(idea);
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${idea.title.toLowerCase().replace(/[^a-z0-9]/g, '-')}-founderos-brief.md`;
  a.click();
  URL.revokeObjectURL(url);
}
